[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-apple-darwin]
# linker = "x86_64-apple-darwin-clang"
linker = "x86_64-apple-darwin21.2-clang"

# ar = "x86_64-apple-darwin-ar"
ar = "x86_64-apple-darwin21.2-ar"

